#
#
#
version: '3'


services:

  hackersguide_www_nginx:
    image: nginx:latest
    container_name: hackersguide_www_nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - hackersguide_www_php


  hackersguide_www_php:
    image: php:7-fpm
    container_name: hackersguide_www_php
    restart: always
    volumes:
      - ./www_site:/www_site 
    env_file:
      - .env

